#if !defined(CONSTANTS__H)
#define CONSTANTS__H

#define MACROPAD_PROFILE_NAME_LENGTH 18
#define MACROPAD_KEY_NAME_LENGTH     4

#define MACROPAD_KEY_MATRIX_WIDTH  4
#define MACROPAD_KEY_MATRIX_HEIGHT 3
#define MACROPAD_KEY_COUNT         (MACROPAD_KEY_MATRIX_WIDTH * MACROPAD_KEY_MATRIX_HEIGHT)

#endif // CONSTANTS__H
